sudo : required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t yoonheechul/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true yoonheechul/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "Docker-App"
  env: "Docker-App-env-1"
  bucker_name: "elasticbeanstalk-ap-southeast-2-643493713545"
  bucker_path: "Docker-App"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
# Add 
# after_success:
#   - echo "Test success"

